LandPortal/LandPortal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from rest_framework import routers, serializers, viewsets
import time

from main.models import Transaction, Block, Chain

class TimestampField(serializers.Field):
    def to_representation(self, value):
        return int(time.mktime(value.timetuple()))
    def to_native(self, value):
        epoch = datetime.datetime(1970,1,1)
        return int((value - epoch).total_seconds())

# Serializers define the API representation.
class TransactionSerializer(serializers.HyperlinkedModelSerializer):
    timestamp = serializers.DateTimeField(format="%s.%f")
    # timestamp = TimestampField("timestamp") 
    class Meta:
        model = Transaction
        fields = [
            "transaction_id",
            "LandHolder_aadhaar",
            "Land_state",
            "Land_district",
            "Land_taluk",
            "Land_village",
            "Land_survey_number",
            "Land_subdivision_number",
	    "Land_hash",
            "timestamp"
        ]

class BlockSerializer(serializers.HyperlinkedModelSerializer):
    timestamp = serializers.DateTimeField(format="%s.%f")
    # timestamp = TimestampField("timestamp") 
    transactions = TransactionSerializer(many=True, read_only=True)

    class Meta:
        model = Block
        fields = [
            "index",
            "transactions",
            "timestamp",
            "previous_hash",
            "nonce",
            "hash"
        ]

class ChainSerializer(serializers.HyperlinkedModelSerializer):
    chain = BlockSerializer(many=True, read_only=True)

    class Meta:
        model = Chain
        fields = [
            "length",
            "chain",
            "peers"
        ]

# ViewSets define the view behavior.
class TransactionViewSet(viewsets.ModelViewSet):
    queryset = Transaction.objects.all()
    serializer_class = TransactionSerializer

class BlockViewSet(viewsets.ModelViewSet):
    queryset = Block.objects.all()
    serializer_class = BlockSerializer

class ChainViewSet(viewsets.ModelViewSet):
    queryset = Chain.objects.all()
    serializer_class = ChainSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'transactions', TransactionViewSet)
router.register(r'blocks', BlockViewSet)
router.register(r'chain', ChainViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

LandPortal/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home, name="home"),
    path('about', views.about, name="about"),
    path('services', views.services, name="services"),
    path('contact', views.contact, name="contact"),
    path('register', views.register, name="register"),
    path('manage', views.manage, name="manage"),
    path('results', views.SearchResultsView.as_view(), name='search_results'),
    path('search', views.search, name='search'),
]

LandPortal/main/models.py
from django.db import models
from django.core.validators import RegexValidator, MinValueValidator
from django.utils import timezone
import uuid

STATE_CHOICES = (("Andhra Pradesh","Andhra Pradesh"),("Arunachal Pradesh ","Arunachal Pradesh "),("Assam","Assam"),("Bihar","Bihar"),("Chhattisgarh","Chhattisgarh"),("Goa","Goa"),("Gujarat","Gujarat"),("Haryana","Haryana"),("Himachal Pradesh","Himachal Pradesh"),("Jammu and Kashmir ","Jammu and Kashmir "),("Jharkhand","Jharkhand"),("Karnataka","Karnataka"),("Kerala","Kerala"),("Madhya Pradesh","Madhya Pradesh"),("Maharashtra","Maharashtra"),("Manipur","Manipur"),("Meghalaya","Meghalaya"),("Mizoram","Mizoram"),("Nagaland","Nagaland"),("Odisha","Odisha"),("Punjab","Punjab"),("Rajasthan","Rajasthan"),("Sikkim","Sikkim"),("Tamil Nadu","Tamil Nadu"),("Telangana","Telangana"),("Tripura","Tripura"),("Uttar Pradesh","Uttar Pradesh"),("Uttarakhand","Uttarakhand"),("West Bengal","West Bengal"),("Andaman and Nicobar Islands","Andaman and Nicobar Islands"),("Chandigarh","Chandigarh"),("Dadra and Nagar Haveli","Dadra and Nagar Haveli"),("Daman and Diu","Daman and Diu"),("Lakshadweep","Lakshadweep"),("National Capital Territory of Delhi","National Capital Territory of Delhi"),("Puducherry","Puducherry"))


#Create your models here.
class FormZero(models.Model):
	date_created = models.DateTimeField("Date Created", default=timezone.now)

class LandDetail(models.Model):
	transaction_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	LandHolder_aadhaar = models.CharField("Aadhaar Number", max_length=20, validators=[RegexValidator(r'^\d{12}$')])
	transaction_time = models.DateTimeField("Time Created", default=timezone.now)

	Land_state = models.CharField("State", choices=STATE_CHOICES, max_length=150)
	Land_district = models.CharField("District", help_text="Enter the District, under whose jurisdiction the Land falls under.", max_length=150)
	Land_taluk = models.CharField("Taluk", max_length=150)
	Land_village = models.CharField("Village", max_length=150)
	Land_survey_number = models.PositiveIntegerField("Survey Number", validators=[MinValueValidator(1)])
	Land_subdivision_number = models.PositiveIntegerField("Subdivision Number", validators=[MinValueValidator(1)])


	def __str__(self):
		return str("TransactionID: " + str(self.transaction_id)+"\nUser: " + str(self.LandHolder_aadhaar))

class Chain(models.Model):
	length = models.PositiveIntegerField("Length")

class Peer(models.Model):
	IP = models.CharField("IP", max_length=150, null=True)
	chain = models.ForeignKey("Chain", related_name='peers', on_delete=models.CASCADE)

class Block(models.Model):
	index = models.PositiveIntegerField("index")

	timestamp = models.DateTimeField("Time Created")
	previous_hash = models.CharField("Previous Hash", max_length=150, null=True)
	nonce = models.PositiveIntegerField("Nonce")
	hash = models.CharField("Hash", max_length=150)

	chain = models.ForeignKey("Chain", related_name='chain', on_delete=models.CASCADE)

	def __str__(self):
		return str("Index: " + str(self.index))

class Transaction(models.Model):
	transaction_id = models.CharField("TransactionID", max_length=150, primary_key=True)

	LandHolder_aadhaar = models.CharField("Aadhaar Number", max_length=12)

	Land_state = models.CharField("State", max_length=150)
	Land_district = models.CharField("District", max_length=150)
	Land_taluk = models.CharField("Taluk", max_length=150)
	Land_village = models.CharField("Village", max_length=150)
	Land_survey_number = models.PositiveIntegerField("Survey Number")
	Land_subdivision_number = models.PositiveIntegerField("Subdivision Number")

	Land_hash = models.CharField("Hash", max_length=150)

	timestamp = models.DateTimeField("Time Created")
	block = models.ForeignKey("Block", related_name='transactions', on_delete=models.CASCADE)

	def __str__(self):
		return str("TransactionID: " + str(self.transaction_id)+"\nUser: " + str(self.LandHolder_aadhaar))

class T2B(models.Model):
	transaction = models.ForeignKey("Transaction", on_delete=models.CASCADE)
	block = models.ForeignKey("Block", on_delete=models.CASCADE)

	def __str__(self):
		return str("BlockID: " + str(self.block.index)+"\nTransactionID: " + str(self.transaction.transaction_id))

class B2C(models.Model):
	block = models.ForeignKey("Block", on_delete=models.CASCADE)
	chain = models.ForeignKey("Chain", on_delete=models.CASCADE)

LandPortal/main/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import LandDetail, FormZero
from django.db import models

class SearchForm(forms.Form):
    query_Aadhaar = forms.CharField(label='Aadhaar to Search', max_length=20)

    def query_Aadhaar(self):
        data = self.cleaned_data['query_Aadhaar']
        data = data.replace('/', '')
        data = data.replace(' ', '')
        return data

class LandForm(forms.ModelForm):
    class Meta:
        model = LandDetail
        fields = ['Land_state', 'Land_district', 'Land_taluk', 'Land_village', 'Land_survey_number', 'Land_subdivision_number']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Confirm'))

class LandDetailsForm(forms.ModelForm):
    class Meta:
        model = LandDetail
        fields = ['LandHolder_aadhaar', 'Land_state', 'Land_district', 'Land_taluk', 'Land_village', 'Land_survey_number', 'Land_subdivision_number']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Confirm'))

    def clean(self):
        cleaned_data = super(LandDetailsForm, self).clean()
        cleaned_data['LandHolder_aadhaar'] = cleaned_data['LandHolder_aadhaar'].replace('/', '')
        cleaned_data['LandHolder_aadhaar'] = cleaned_data['LandHolder_aadhaar'].replace(' ', '')
        return cleaned_data

class ZeroForm(forms.ModelForm):
    class Meta:
        model = FormZero
        fields = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Mine'))

LandPortal/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import LandDetailsForm, ZeroForm, LandForm
from .models import Transaction, Block, T2B, Chain
from django.shortcuts import redirect
from django.contrib import messages
from datetime import datetime
from django.db.models import Q
from django.views.generic import TemplateView, ListView

import requests
import json
from hashlib import sha256

CONNECTED_NODE_ADDRESS = "http://127.0.0.1:8001"
THIS_ADDRESS = "http://127.0.0.1"

# Create your views here.
t_data = []
b_data = []

def compute_hash(data):
    """
    A function that return the hash of the block contents.
    """
    block_string = json.dumps(data, sort_keys=True)
    return sha256(block_string.encode()).hexdigest()

def update():
    get_chain_address = "{}/chain".format(CONNECTED_NODE_ADDRESS)
    this_chain_address = "{}/api/chain".format(THIS_ADDRESS)
    response = requests.get(get_chain_address)
    curr_chain = requests.get(this_chain_address)
    if response.status_code == 200:
        chain = json.loads(response.content)
        try:
            this_chain = json.loads(curr_chain.content)[0]
            print("* {} blocks in client {} blocks in origin".format(len(this_chain["chain"]), len(chain["chain"])))
            flag = len(chain["chain"]) >= len(this_chain["chain"])
        except:
            this_chain = []
            flag = True
        if flag:
            print("* Recreating Chain from Blockchain")
            Chain.objects.all().delete()
            c = Chain(
                length=len(chain["chain"])
            )
            c.save()
            for block in chain["chain"]:
                new_b_hash = block['hash']
                try:
                    transact = Block.objects.get(hash=new_b_hash)
                except Block.DoesNotExist:
                    b = Block(
                        index=block["index"],
                        timestamp=datetime.fromtimestamp(float(block["timestamp"])),
                        previous_hash=block["previous_hash"],
                        nonce=block["nonce"],
                        hash=block["hash"],

                        chain=c
                    )
                    b.save()
                for tran in block["transactions"]:
                    new_t_id = tran['transaction_id']
                    try:
                        transact = Transaction.objects.get(transaction_id=new_t_id)
                    except Transaction.DoesNotExist:
                        t = Transaction(
                            transaction_id=tran["transaction_id"], 

                            LandHolder_aadhaar=tran["LandHolder_aadhaar"], 

                            Land_state=tran["Land_state"], 
                            Land_district=tran["Land_district"], 
                            Land_taluk=tran["Land_taluk"], 
                            Land_village=tran["Land_village"], 
                            Land_survey_number=tran["Land_survey_number"],
                            Land_subdivision_number=tran["Land_subdivision_number"],
                            Land_hash=tran["Land_hash"],

                            timestamp=datetime.fromtimestamp(float(tran["timestamp"])),
                            block=b
                        )

                        t.save()

                        link1 = T2B(
                            transaction=t,
                            block=b
                        )
                        link1.save()
        else:
            print("* Syncing Blockchain")
            update_chain_address = "{}/update".format(CONNECTED_NODE_ADDRESS)
            requests.post(update_chain_address)

def home(request):
    return render(request=request, template_name="main/index.html")

def about(request):
    return render(request=request, template_name="main/about.html")

def services(request):
    return render(request=request, template_name="main/services.html")

def contact(request):
    return render(request=request, template_name="main/contact.html")

def search(request):
    if request.method == "POST":
        form = LandForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)

            # Things to do before save
            hash_object = {
                'Land_state': data.Land_state,
                'Land_district': data.Land_district,
                'Land_taluk': data.Land_taluk,
                'Land_village': data.Land_village,
                'Land_survey_number': data.Land_survey_number,
                'Land_subdivision_number': data.Land_subdivision_number
            }

            search_hash = compute_hash(hash_object)

            object_list = Transaction.objects.filter(
                Q(Land_hash__icontains=search_hash)
            )

            return render(request=request, template_name="main/results.html", context={'object_list': object_list, 'query': search_hash}  )
    else:
        form = LandForm()
    return render(request=request, template_name="main/search.html", context={'form': form})

class SearchResultsView(ListView):
    model = Transaction
    template_name="main/results.html"

    def get_queryset(self): # new
        query = self.request.GET.get('q')
        object_list = Transaction.objects.filter(
            Q(LandHolder_aadhaar__icontains=query)
        )
        return object_list

    def get_context_data(self,**kwargs):
        context = super(SearchResultsView,self).get_context_data(**kwargs)
        context["query"] = self.request.GET.get('q')
        return context

def manage(request):
    if request.method == "POST":
        form = ZeroForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)

            # Things to do before save
            

            # Submit a transaction
            new_tx_address = "{}/mine".format(CONNECTED_NODE_ADDRESS)
            msg = requests.get(new_tx_address,
                     headers={'Content-type': 'application/json'})

            # messages.info(request, msg)
            # data.save()
            update()
            return redirect(to='main:manage')
    else:
        form = ZeroForm()
    return render(request=request, template_name="main/manage.html", context={'form': form})

def register(request):
    if request.method == "POST":
        form = LandDetailsForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)

            # Things to do before save
            hash_object = {
                'Land_state': data.Land_state,
                'Land_district': data.Land_district,
                'Land_taluk': data.Land_taluk,
                'Land_village': data.Land_village,
                'Land_survey_number': data.Land_survey_number,
                'Land_subdivision_number': data.Land_subdivision_number
            }

            my_hash = compute_hash(hash_object)

            data_object = {
                'transaction_id': str(data.transaction_id),

                'LandHolder_aadhaar': data.LandHolder_aadhaar,

                'Land_state': data.Land_state,
                'Land_district': data.Land_district,
                'Land_taluk': data.Land_taluk,
                'Land_village': data.Land_village,
                'Land_survey_number': data.Land_survey_number,
                'Land_subdivision_number': data.Land_subdivision_number,

                'Land_hash' : my_hash
            }

            # Submit a transaction
            new_tx_address = "{}/new_transaction".format(CONNECTED_NODE_ADDRESS)
            msg = requests.post(new_tx_address,
                      json=data_object,
                     headers={'Content-type': 'application/json'})

            messages.info(request, msg)
            # data.save()
            return redirect(to='main:home')
    else:
        form = LandDetailsForm()
        form.fields['LandHolder_aadhaar'].widget.attrs['maxlength'] = '20'
    return render(request=request, template_name="main/register.html", context={'form': form})

LandPortal/main/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
	<section class="hero-wrap hero-wrap-2 ftco-degree-bg js-fullheight" style="background-image: url(' {% static 'main/images/bg_1.jpg' %} ');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate pb-5 text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href=" {% static 'main/index.html' %} ">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>About us <i class="ion-ios-arrow-forward"></i></span></p>
            <h1 class="mb-3 bread">About Us</h1>
          </div>
        </div>
      </div>
  </section>

	{% include "main/fragments/about_f.html" %}

{% endblock %}

LandPortal/main/templates/main/base.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Land Registration Portal</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href=" {% static 'main/css/open-iconic-bootstrap.min.css' %} ">
    <link rel="stylesheet" href=" {% static 'main/css/animate.css' %} ">
    
    <link rel="stylesheet" href=" {% static 'main/css/owl.carousel.min.css' %} ">
    <link rel="stylesheet" href=" {% static 'main/css/owl.theme.default.min.css' %} ">
    <link rel="stylesheet" href=" {% static 'main/css/magnific-popup.css' %} ">

    <link rel="stylesheet" href=" {% static 'main/css/aos.css' %} ">

    <link rel="stylesheet" href=" {% static 'main/css/ionicons.min.css' %} ">

    <link rel="stylesheet" href=" {% static 'main/css/bootstrap-datepicker.css' %} ">
    <link rel="stylesheet" href=" {% static 'main/css/jquery.timepicker.css' %} ">

    
    <link rel="stylesheet" href=" {% static 'main/css/flaticon.css' %} ">
    <link rel="stylesheet" href=" {% static 'main/css/icomoon.css' %} ">
    <link rel="stylesheet" href=" {% static 'main/css/style.css' %} ">
  </head>
  <style>
    .google-maps {
        position: relative;
        padding-bottom: 75%; // This is the aspect ratio
        height: 0;
        overflow: hidden;
    }
    .google-maps iframe {
        position: absolute;
        top: 0;
        left: 0;
        width: 100% !important;
        height: 100% !important;
    }
</style>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href=" {% url 'main:home' %} ">Land Registration Portal</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item active"><a href=" {% url 'main:home' %} " class="nav-link">Home</a></li>
	          <li class="nav-item"><a href=" {% url 'main:about' %} " class="nav-link">About</a></li>
	          <li class="nav-item"><a href=" {% url 'main:services' %} " class="nav-link">Services</a></li>
	          <li class="nav-item"><a href=" {% url 'main:register' %} " class="nav-link">Register</a></li>
            <li class="nav-item"><a href=" {% url 'main:search' %} " class="nav-link">Search</a></li>
	          <li class="nav-item"><a href=" {% url 'main:manage' %} " class="nav-link">Manage</a></li>
	          <li class="nav-item"><a href=" {% url 'main:contact' %} " class="nav-link">Contact</a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->
    
    {% block content %}
	  {% endblock %}

    <footer class="ftco-footer ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Land Registration Portal</h2>
              <p>The most convienient, and the secure way to register lands.</p>
              <ul class="ftco-footer-social list-unstyled mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-4">
              <h2 class="ftco-heading-2">Services Offered</h2>
              <ul class="list-unstyled">
                <li><a href="{% url 'main:search' %}"><span class="icon-long-arrow-right mr-2"></span>Search Properties</a></li>
                <li><a href="{% url 'main:register' %}"><span class="icon-long-arrow-right mr-2"></span>Register Properties</a></li>
                <li><a href="{% url 'main:register' %}"><span class="icon-long-arrow-right mr-2"></span>Apply for Review</a></li>
                <li><a href="{% url 'main:services' %}"><span class="icon-long-arrow-right mr-2"></span>FAQs</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-4">
              <h2 class="ftco-heading-2">About Us</h2>
              <ul class="list-unstyled">
                <li><a href="{% url 'main:services' %}"><span class="icon-long-arrow-right mr-2"></span>How it Works?</a></li>
                <li><a href="https://github.com/L4TTiCe"><span class="icon-long-arrow-right mr-2"></span>Github : User</a></li>
                <li><a href="https://github.com/L4TTiCe/LandRegistrationPortal"><span class="icon-long-arrow-right mr-2"></span>Github : Project Source</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Company</h2>
              <ul class="list-unstyled">
                <li><a href="{% url 'main:contact' %}"><span class="icon-long-arrow-right mr-2"></span>About Us</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Press</a></li>
                <li><a href="{% url 'main:contact' %}"><span class="icon-long-arrow-right mr-2"></span>Contact</a></li>
                <li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Careers</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">VIT University, Vellore, Tamilnadu, India</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+91 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope pr-4"></span><span class="text">helpdesk@landreg.gov</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">
	
            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src=" {% static 'main/js/jquery.min.js' %} "></script>
  <script src=" {% static 'main/js/jquery-migrate-3.0.1.min.js' %} "></script>
  <script src=" {% static 'main/js/popper.min.js' %} "></script>
  <script src=" {% static 'main/js/bootstrap.min.js' %} "></script>
  <script src=" {% static 'main/js/jquery.easing.1.3.js' %} "></script>
  <script src=" {% static 'main/js/jquery.waypoints.min.js' %} "></script>
  <script src=" {% static 'main/js/jquery.stellar.min.js' %} "></script>
  <script src=" {% static 'main/js/owl.carousel.min.js' %} "></script>
  <script src=" {% static 'main/js/jquery.magnific-popup.min.js' %} "></script>
  <script src=" {% static 'main/js/aos.js' %} "></script>
  <script src=" {% static 'main/js/jquery.animateNumber.min.js' %} "></script>
  <script src=" {% static 'main/js/bootstrap-datepicker.js' %} "></script>
  <script src=" {% static 'main/js/jquery.timepicker.min.js' %} "></script>
  <script src=" {% static 'main/js/scrollax.min.js' %} "></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src=" {% static 'main/js/google-map.js' %} "></script>
  <script src=" {% static 'main/js/main.js' %} "></script>
  {% block script %}
	{% endblock %}
  <script>
    $(document).ready(function(){
        $('.toast').toast('show')
    });
    </script>
  </body>
</html>

LandPortal/main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
	<div class="hero-wrap ftco-degree-bg" style="background-image: url(' {% static 'main/images/bg_1.jpg' %} ');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text justify-content-center align-items-center">
          <div class="col-lg-8 col-md-6 ftco-animate d-flex align-items-end">
          	<div class="text text-center">
	            <h1 class="mb-4">Most Convinient <br>Way to Register Property</h1>
	            <p style="font-size: 18px;">Register your properties in an effortless and paperless fasion, using the relaibility and the security offered by Blockchains.</p>
	            <form method="get" action="{% url 'main:search_results' %}" class="search-location mt-md-5">
					<div class="row justify-content-center">
						<div class="col-lg-10 align-items-end">
							<div class="form-group">
							<div class="form-field">
								<input name="q" type="text" class="form-control" placeholder="Search Aadhaar">
								<button type="submit"><span class="ion-ios-search"></span></button>
							</div>
							</div>
						</div>
					</div>
				</form>
            </div>
          </div>
        </div>
      </div>
      <div class="mouse">
				<a href="#" class="mouse-icon">
					<div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
				</a>
			</div>
    </div>

    {% include "main/fragments/services_f.html" %}

    {% include "main/fragments/hiw_f.html" %}

    {% include "main/fragments/about_f.html" %}

{% endblock %}